# Generated by Django 5.1.3 on 2025-02-15 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_photo_application_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='image',
            new_name='photo',
        ),
    ]
