# Generated by Django 5.1.3 on 2025-02-15 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_application_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='stat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applic_stat', to='myapp.stat', verbose_name='Статус'),
        ),
    ]
