# Generated by Django 4.2 on 2025-02-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_application_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
    ]
