# Generated by Django 4.2 on 2025-02-17 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_application_is_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='image_after',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='application',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='stat',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applic_stat', to='myapp.stat', verbose_name='Статус'),
        ),
    ]
